### ISSUE TITLE
Suggestion: Reusing exist window

### ISSUE THREAD

**Issue by kukushi** [mpco/AlfredWorkflow-DEVONthink-Search#11]
When using `dnts` start a new search, there will always l be a new DEVONThink window opened. It's annoying too much windows opened.
If It is possible to reuse an existing window to start the search?

**Comment by mpco** [comment]
I will try to make it.

**Comment by mpco** [comment]
Which version of DEVONthink are you using? 2.x or 3.x?

You can use the latest release v7.3 to search in existing window for DNt 3.x.

**Comment by kukushi** [comment]
@mpco I'm using DEVONthink 3.x and Alfred 3.x.
I have tried the latest release and I found it doesn't compatible with Alfred 3.x.

**Comment by mpco** [comment]
Try this version: [Workflow for Alfred 3.zip](https://github.com/mpco/AlfredWorkflow-DEVONthink-Search/files/3296739/Workflow.for.Alfred.3.zip)

**Comment by kukushi** [comment]
@mpco I appreciate your work but It will still open a new window.

**Comment by mpco** [comment]
Try the latest release https://github.com/mpco/AlfredWorkflow-DEVONthink-Search/releases/tag/7.4
