### ISSUE TITLE
一个小问题

### ISSUE THREAD

**Issue by hjianyi** [mpco/AlfredWorkflow-DEVONthink-Search#12]
在 `search.js` 中，

```
if (itemLocation.length > 1) {
	itemLocation = itemLocation.slice(0, -1).replace(/\//g, " > ")
} else {
	itemLocation = ""
}
```

这段代码替换了 `/`，但是之后的代码

```
if (itemLocation == "/Tags/") {
	item["title"] = "[Tag] " + itemName
}
```

使用了替换了 `/` 的路径来判定 record 是否为 tag 。

这里可以改为 `if (record.location()  == "/Tags/")`。

或者使用 record 的 `tagType` 属性来判断 record 是否为 tag。

```
function isTag(record) {
	return (record.type() == "group") && (record.tagType() !== "no tag")
}
```

https://discourse.devontechnologies.com/t/determining-whether-a-group-is-a-user-tag-or-not/9253/2

> V2.0.3 will add a “tag type” property returning either no tag (no group or excluded from tagging), group tag (outside of Tags group) or ordinary tag (inside of Tags group)

**Comment by mpco** [comment]
感谢反馈！
