### ISSUE TITLE
Suggestion: unified search

### ISSUE THREAD

**Issue by haakonstorm** [mpco/AlfredWorkflow-DEVONthink-Search#13]
### Thank you for creating this. 

**Awesome** workflow, especially now in combination with the new Devonthink!

### Suggestions:
- Unified / advanced search
- Tab-completion on #tag and in:db
- Friendly names for databases

### **`dnt search_terms [#tag] [y:year] [in:db]`**   
-->    

|  term | description | example |
| -|-|-|
| `search_terms`  | one or more fulltext search terms | `car repair manual` |
| `#tag`| tag | `#tesla` `#manual` |
| ` | tag | `#tesla` |
| `y:`  | year or range | `y:2018` |
|       |               | `y:2018..2019` |
|       |               | `y:18` |
|       |               | `y:18...19` |
|       |               | `y:18-19` |
| `in:`  | search in database | `in:ref` |
|   |  | `in:ref` `in:main`|
|   |  | `in:2` |
|   |  | `in:2,3` |

### Tab completion 
- Start typing `#te`, **in-line list** appears `tesla/team/text/..`, select to autocomplete tag

### Assign Friendly Names
- Assign short Friendly Names to databases, or even simple numbering
- `"manuals and reference material.dtDb"` --> `1` or `ref`
- **Example:**  `dnt repair #tesla in:ref`

### Tab completion for databases

- **Start typing** `in:`
  - **list appears** 
    - `main database1............. main`
    - `manuals and ref............ ref` 
    - `archived................... arch`
  - **select to autocomplete** database name
  - _(or numbered)_
    - `main database1............. 1`
    - `manuals and ref............ 2` 
    - `archived................... 3`

**Comment by mpco** [comment]
Sorry, I don't have time to finish it.
