### ISSUE TITLE
Opening Results - How to Change?

### ISSUE THREAD

**Issue by jasondm007** [mpco/AlfredWorkflow-DEVONthink-Search#16]
Thanks for sharing this Alfred workflow for DEVONthink. It's fantastic!

One quick question: Is it possible to switch the default search results action to open the file in DEVONthink (i.e., instead of an external editor)? 

I tried merely adapting the configured connection between workflow actions, so that the "Open With External Editor" requires users to hold command and the "Open with DEVONthink" doesn't require anything, but it doesn't seem to work. From what I can tell, the script filter is passing the file path to the "Open with DEVONthink" action instead of the UUID? Is there a minor change that can be done to the script filter or the search.js file to accomplish this?

Thanks for your help! And, thanks again for sharing this workflow!!

**Comment by zeltak** [comment]
+1 to that, i would also really like the results to open in DT by default! 
any chance this can be configured?

thx for your great work

Z

**Comment by bcdavasconcelos** [comment]
I changed the workflow behavior. See [this branch here](https://github.com/bcdavasconcelos/AlfredWorkflow-DEVONthink-Search/tree/Open_in_DT3).

**Comment by zeltak** [comment]
perfect ! Thx so much @bcdavasconcelos !!

Z
