### ISSUE TITLE
Access custom meta data?

### ISSUE THREAD

**Issue by swj1442291549** [mpco/AlfredWorkflow-DEVONthink-Search#17]
New to javascript with AppleScript. Just wonder how to read custom meta data of the record.

Would be great if you could give an easy example?

**Comment by mpco** [comment]
```AppleScript
tell application "DEVONthink 3"
	set theRecord to (get record with uuid "1967582A-890A-42D2-AC94-DE9A1E69E6F2")
	get custom meta data for "metaDataName" from theRecord
end tell
```

![image](https://user-images.githubusercontent.com/3690653/82672534-0d81bd80-9c73-11ea-9d47-877cbbe17b58.png)

**Comment by swj1442291549** [comment]
Great thanks for your help.

Actually I have figured out how to read custom data with AppleScript, but I don't know how to do it with javascript (implemented in `search.js` as line 47)
`var itemName = record.name()`

**Comment by mpco** [comment]
```javascript
DNt.getCustomMetaData({for: "metaDataName", from: record})
```

**Comment by swj1442291549** [comment]
Great thanks :)
