### ISSUE TITLE
‘dnf' isn’t working for me

### ISSUE THREAD

**Issue by pfarrelle** [mpco/AlfredWorkflow-DEVONthink-Search#18]
All of the other filter commands are working but ‘dnf' does not.  After typing ‘dn' I see “List Favorites" as the top choice in the Alfred window.  If I hit return, or follow through with the final ‘f', then I fall out of your workflow to a Google search for ‘dnf'.  I am running version 7.4 of your workflow and DT3 3.0.4.

**Comment by mpco** [comment]
Probably because there is no favorite item in DEVONthink.

**Comment by pfarrelle** [comment]
Hi Charles - thanks for the quick replay. Unfortunately I do have (a lot of) favorites (see attached).

Thanks, Paul

**Comment by mpco** [comment]
Please post the workflow log here. 
If you don’t know how to get the log, follow these steps:

1. run `?devonthink search` in Alfred to open DEVONthink workflow.
2. press `⌘Command+D` to open Alfred debug mode.
3. run `dnf` to get the log text.
4. copy the log and post here.

**Comment by pfarrelle** [comment]
Here is the log

[11:08:53.059] Logging Started...
[11:09:00.873] DEVONthink Search[Script Filter] Queuing argument '(null)'
[11:09:01.082] DEVONthink Search[Script Filter] Script with argv '(null)' finished
[11:09:01.084] ERROR: DEVONthink Search[Script Filter] Code 1: Traceback (most recent call last):
  File "getFavorites.py", line 15, in <module>
    "title": plobj["Name"],
KeyError: 'Name'

I have also attached screenshots of the Alfred window after typing “dn" and then “dnf".

Hope this helps.

Thanks, Paul

**Comment by mpco** [comment]
Sorry, I can't see the attached images on github web.

Could you upload the Favorites.plist file?
path: `~/Library/Application Support/DEVONthink 3/Favorites.plist`

GitHub does not support uploading plist file, so compress it and upload.

**Comment by pfarrelle** [comment]
here you go ...

Thanks, Paul

**Comment by pfarrelle** [comment]
[Favorites.plist.zip](https://github.com/mpco/AlfredWorkflow-DEVONthink-Search/files/4672397/Favorites.plist.zip)

**Comment by pfarrelle** [comment]
closed the topic by mistake ...

**Comment by mpco** [comment]
On my computer, `dnf` works well with your Favorites.plist file. I can not found the reason.

You can try to delete this workflow and reinstall it.
If you still cannot use `dnf`, then do the following:

1. Download [getFavorites.py.zip](https://github.com/mpco/AlfredWorkflow-DEVONthink-Search/files/4672868/getFavorites.py.zip) to Downloads folder.
2. Uncompress it.
3. Open Terminal.app, then paste `/usr/bin/python ~/Downloads/getFavorites.py` and press Enter.
4. copy the result and post here.

**Comment by pfarrelle** [comment]
Downloaded a fresh version with the same result.

Here is the zipped output from your python module.


Thanks, Paul

**Comment by mpco** [comment]
Sorry, I can't see the output on github web.

**Comment by pfarrelle** [comment]
[dnfOutput.zip](https://github.com/mpco/AlfredWorkflow-DEVONthink-Search/files/4675077/dnfOutput.zip)

**Comment by pfarrelle** [comment]
sorry - I just replied through my mail client, instead of dragging to GitHub web.

**Comment by mpco** [comment]
The output looks ok, I can't find the reason, sorry.
