### ISSUE TITLE
这个不错，终于有好用的搜索工具了

### ISSUE THREAD

**Issue by oit63** [mpco/AlfredWorkflow-DEVONthink-Search#2]
买了dv 两三年了，一直对这个搜索问题头痛，终于找到个解决方案。感谢

**Comment by tenhow** [comment]
下一步扩充可以参考下evernote的 @ 和 #
https://www.alfredforum.com/topic/840-evernote-workflow-9-beta-3/

**Comment by tenhow** [comment]
这家的随手记也不错
https://github.com/dvcrn/alfred-devonthink
