### ISSUE TITLE
搜索没有结果显示

### ISSUE THREAD

**Issue by ma3252788** [mpco/AlfredWorkflow-DEVONthink-Search#20]
已经进行了授权，但是输入`dnt 关键词 `  搜索的时候，没有任何下拉结果出现，但是输入`dnd`会出现数据库选择，这样应该代表了授权成功了吧？

但是为什么不能正常搜索呢？

谢谢大大~

**Comment by ma3252788** [comment]
> 这个时间显然太长了，是不是你的文档非常多？

大概2000篇笔记吧，确实感觉有点长。。主要是在DEVON内部就很快，瞬间就出来了

**Comment by mpco** [comment]
可能就是因为文档太多了
不过这个程序本身就有性能问题，难以处理大量文件的情况
无奈水平太差无力解决……

你可以在 Alfred 中创建一个 Web search，链接为 `x-devonthink://search?query={query}`，设置个关键词比如 `dd`
这样就可以输入 `dd 搜索词` 直接打开 DEVONthink 搜索

**Comment by ma3252788** [comment]
> 可能就是因为文档太多了
> 不过这个程序本身就有性能问题，难以处理大量文件的情况
> 无奈水平太差无力解决……
> 
> 你可以在 Alfred 中创建一个 Web search，链接为 `x-devonthink://search?query={query}`，设置个关键词比如 `dd`
> 这样就可以输入 `dd 搜索词` 直接打开 DEVONthink 搜索

谢谢，您说的这种方法也不错，那我暂时就先用这种啦。
