### ISSUE TITLE
macOS Catalina 上的权限问题

### ISSUE THREAD

**Issue by lloyar** [mpco/AlfredWorkflow-DEVONthink-Search#23]
第一次运行该 Workflow 时没有弹出授权。系统偏好设置的自动化中，Alfred 只拥有控制 Finder 和 Music 的权限，没有控制 DEVONthink 的权限，另外 dnd 直接触发不了。我该怎么办呢?
Alfred 版本是 4.1.1[1172]
DEVONthink 版本 3.5.2

**Comment by JimmyLv** [comment]
我的 dnd 也触发不了，工作流就 GG 了，
唉 -，-
