### ISSUE TITLE
How am I supposed to install this?

### ISSUE THREAD

**Issue by tonywatkins** [mpco/AlfredWorkflow-DEVONthink-Search#24]
I don't have a clue what to do with all the files, and there is nothing in the readme to tell me what to do. Could there be a .alfredworkflow download?

**Comment by shugenja** [comment]
Pasting the creator’s instructions here, from [this site](https://discourse.devontechnologies.com/t/alfred-workflow-for-dt-3-x/46778/9).

1. Open the releases webpage of Github repo: https://github.com/mpco/AlfredWorkflow-DEVONthink-Search/releases 157

2. Click the DEVONthink.Search.alfredworkflow file to download.

**Comment by tonywatkins** [comment]
Thanks.
