### ISSUE TITLE
Alfred

### ISSUE THREAD

**Issue by dullboyliu** [mpco/AlfredWorkflow-DEVONthink-Search#3]
你好，刚刚上手devonthink，里面的中文搜索让我忍无可忍，幸好发现你做的workflow。但是下载最新版以后，发现无法搜索，如下图。
<img width="600" alt="screenshot_2019-02-18 15 00 25_bae7tq" src="https://user-images.githubusercontent.com/26785478/52933690-19efda00-338f-11e9-9fca-09a06e766434.png">
我自己做了一个较为简单可以搜索的（电脑小白，纯粹照猫画虎），如下图
<img width="833" alt="screenshot_2019-02-18 15 00 59_qur374" src="https://user-images.githubusercontent.com/26785478/52933724-32f88b00-338f-11e9-8d34-3bddef33539a.png">
<img width="677" alt="screenshot_2019-02-18 15 00 46_elfl7q" src="https://user-images.githubusercontent.com/26785478/52933730-3724a880-338f-11e9-8cfd-fd9c6ea2d89a.png">
这样做虽然可以搜索，但无法建立用默认程序打开等动作，只能在devonthink中显示搜索项。不知道是什么问题，希望你可以帮我解决。谢谢！

**Comment by mpco** [comment]
你用的是 DEVONthink Pro Office 吗？

**Comment by dullboyliu** [comment]
太棒了，谢谢回复！希望你能帮我解决苦恼！
对，我用的是devonthink pro office，其自带的搜索对中文简直是残忍。想用alfred解决以下问题：
1、提高搜索功能
2、搜索时alfred的备注信息是该词条在database的路径，如work>research>sociology，而不是其在finder中的位置
3、在alfred以不同方式打开（用系统默认软件、用devonthink自带的小窗口编辑器、在devonthink中）
4、在不同database里搜索
谢谢！

**Comment by mpco** [comment]
https://github.com/mpco/AlfredWorkflow-DEVONthink-Search/files/2651576/coreSearchScript.zip

下载解压双击打开，按下 Command+R 快捷键运行，看看结果。这段代码是这个 Workflow 的核心。
把结果贴上来。

**Comment by dullboyliu** [comment]
多谢！这是结果
"{\"items\":[{\"type\":\"file\",\"title\":\"DEVONthink Pro Search\",\"score\":1,\"arg\":\"/Users/lmy/Library/Application Support/DEVONthink Pro 2/Inbox.dtBase2/Files.noindex/webarchive/f/DEVONthink Pro Search.webarchive\",\"subtitle\":\"🗄 Inbox /\",\"icon\":{\"type\":\"fileicon\",\"path\":\"/Users/lmy/Library/Application Support/DEVONthink Pro 2/Inbox.dtBase2/Files.noindex/webarchive/f/DEVONthink Pro Search.webarchive\"}}]}"

**Comment by mpco** [comment]
看这个结果挺正常啊，你要不换几个词再试试这个 Workflow ？

**Comment by dullboyliu** [comment]
试了，中文的英文的都试了，就是不管用，崩溃死了。。。

**Comment by dullboyliu** [comment]
这个跟我database的存放路径有关吗？我建立了几个database都放在document文件夹里了

**Comment by mpco** [comment]
与路径无关，只要是 DEVONthink 已打开的数据库都能搜索。

你可以在 DEVONthink 中按下 Shift+Command+F 搜索下试试，它和这个 Workflow 的结果是一致的。

**Comment by dullboyliu** [comment]
直接用devonthink搜也几乎什么搜不出来，必须汉字前加~，这就可以搜出来了，但是alfred的workflow还是搜不出。如图。

**Comment by dullboyliu** [comment]
来来回回重装了几次devonthink，这下连之前可以用的那个workflow都没办法用了。。。

**Comment by mpco** [comment]
我也不知道你为啥用不了。如果愿意，可以留个邮箱啥的，之后用 TeamViewer 帮你远程查看下

**Comment by dullboyliu** [comment]
太感谢了！48856454@qq.com <mailto:48856454@qq.com>，直接邮箱联系吧。

> 在 2019年2月21日，下午9:39，Charles Ma <notifications@github.com> 写道：
> 
> TeamViewer
