### ISSUE TITLE
Feature Request - Open DEVONthink Workspaces

### ISSUE THREAD

**Issue by zeitchef** [mpco/AlfredWorkflow-DEVONthink-Search#4]
Great workflow! I'm working heavily with the workspaces feature in DEVONthink Pro and I was wondering if it might be possible to be able to open a particular workspace from Alfred. Perhaps a `dnw` command that lets you select a particular workspace? Just a thought!

**Comment by mpco** [comment]
After a preliminary look, I feel that it should be feasible. I will do it later.

**Comment by mpco** [comment]
Look at the new version: https://github.com/mpco/AlfredWorkflow-DEVONthink-Search/releases/tag/6.0

**Comment by zeitchef** [comment]
Works exactly as I imagined. Great work! And the search feature is also killer.

I will mention this workflow to the DEVONthink people, as it's clearly a superior workflow to the one they link on their website, which is not actively developed any longer. Great work, again!
