### ISSUE TITLE
Supports Devonthink 3

### ISSUE THREAD

**Issue by heleeos** [mpco/AlfredWorkflow-DEVONthink-Search#5]
[Devonthink 3](https://www.devontechnologies.com/blog/devonthink-30b1) released just few days ago. Though this workflow works [modifying a few parts in your code](https://github.com/heleeos/AlfredWorkflow-DEVONthink-Search/tree/dt3), I wish your workflow supports Devonthink 3 officially.

**Comment by vigorjohn** [comment]
Yes，Devomthink 3 is beautiful, please do this great job! Thanks!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mpco** [comment]
The new version https://github.com/mpco/AlfredWorkflow-DEVONthink-Search/releases/tag/7.0 has been uploaded. Please feedback if it has any problem.
