### ISSUE TITLE
List tags command in version 7.0 seems to be broken

### ISSUE THREAD

**Issue by bojangles007** [mpco/AlfredWorkflow-DEVONthink-Search#7]
Thanks for updating your alfred-devonthink integration so quickly.

The keyboard combination ⌘Command + Enter to list all tags in the database (after having chosen several different databases) doesn't seem to work for me.

Pressing the ⌘Command key changes the subtitle of the database name to "Open with Devonthink", but there is no  taglist.

Am I missing something?

TIA!

**Comment by mpco** [comment]
To display a list of tags for a database: 
1. Enter `dnd` to display a list of databases. 
2. Select a database and press Cmd+enter to display its tag list.

When the database list is displayed after `dnd` is entered, pressing Cmd key will cause the subtitle to display as "Press Enter to list all Tags in the database".

**Comment by bojangles007** [comment]
yeap ----- its working as designed!
Thx!
