### ISSUE TITLE
devonthink 3据说加强了中文支持，但我感觉反而不如以前啊，有什么技巧吗？

### ISSUE THREAD

**Issue by woyaojizhu8** [mpco/AlfredWorkflow-DEVONthink-Search#8]
新版增强了中文分词，但是这样一来就完全把分词以后的中文当成英文来处理了，比如一篇文档包含“加强了中文支持”，搜索“加强了支持”也能搜到，搜索“文”则搜不到。可是中文跟英文不一样，中文的每个字基本都是有含义的，不像英文字母无意义。以前还可以用～实现理想的匹配效果，就是简单的字符串匹配，现在新版～也失效了。请问有什么技巧能够实现以前～的匹配效果吗？
不好意思我不是这个脚本的用户，也不是alfred用户，但是因为觉得这里可能有希望获得相关信息，就来这里提问一下，希望作者不要介意。

**Comment by mpco** [comment]
欢迎探讨问题~

根据我的测试和应用帮助文档，`~`并没有失效。

![Screen Shot 2019-05-20 at 23 39 28](https://user-images.githubusercontent.com/3690653/58034185-8af28980-7b58-11e9-8a82-d5ba0d44bf7b.png)

**Comment by woyaojizhu8** [comment]
嗯，我刚刚试了好多，情况更加复杂，貌似是这样：如果是四字词语，比如“争权夺利”，搜索“～权”、“～夺”、“～利”都能搜到，但是搜“～权夺”、“～夺利”这种都搜不到。对于两字词语，～是没有失效的，所以大部分情况下～没失效了。

**Comment by mpco** [comment]
可能“争权夺利”已经被分词为 争权 和 夺利 了，所以“～权夺”无法搜到。

**Comment by woyaojizhu8** [comment]
@mpco 并不是，分词情况在右侧栏是可以看到的，“争权夺利”确实被分成一个词了。我可以这么理解：如果用～这个符号，～和它之后的一个字就会被视为一个词，所以“～权夺”被分成“～权”和“夺”两个词语，就匹配不到“争权夺利”了

**Comment by mpco** [comment]
～权夺 的意思是含有 权夺 的词语或语句，至于为什么有问题就不知道了。可以到官方论坛反馈试试。

**Comment by mpco** [comment]
刚发布了 3.0beta2 版本，更新说明中提到进一步改善亚洲语言支持，不知道你的问题有没有解决？

**Comment by woyaojizhu8** [comment]
@mpco 没有变化

**Comment by mpco** [comment]
可以参考这篇文章 https://sspai.com/post/54552 中的方法，重建数据库试试
